import json
import time
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

class MockLLMProvider:
    """
    Highly configurable Mock provider that simulates various LLM failure states
    and responses for comprehensive unit testing without spending real money.
    """
    def __init__(self, simulate_latency_sec: float = 2.0, failure_rate: float = 0.0):
        self.latency = simulate_latency_sec
        self.failure_rate = failure_rate
        self.call_count = 0
        
    def generate_content(self, prompt: str) -> Dict[str, Any]:
        """
        Simulates the delay and structured output of generative inference.
        """
        logger.info(f"MockLLM received prompt length: {len(prompt)}")
        self.call_count += 1
        
        # Simulate network delay simulating heavy computation
        time.sleep(self.latency)
        
        # Determine if we simulate an outage
        if self.failure_rate > 0.0:
            import random
            if random.random() < self.failure_rate:
                logger.error("MockLLM simulating model outage/rate limit.")
                raise ConnectionError("Mock simulated API 503 Service Unavailable")
                
        # Return a structurally perfect mock payload
        mock_payload = {
            "snapshot": {
                "description": "MOCK GENERATION: This is a robust mock report for CI/CD.",
                "domains": ["Unit Testing", "Mock Data"],
            },
            "executiveSummary": {
                "status": [
                    {"label": "Trend", "value": "Stable", "type": "positive"}
                ],
                "text": "The mock metrics demonstrate perfect synthetic correlation."
            },
            "technicalSignals": [
                {"name": "MOCK_MACD", "status": "Neutral", "text": "Signal generated by MockLLMProvider"}
            ],
            "outlook": {
                "shortTerm": "Mock short term expectation",
                "longTerm": "Mock long term expectation"
            }
        }
        
        return mock_payload
        
    def get_telemetry(self) -> Dict[str, Any]:
        return {
            "calls_made": self.call_count,
            "simulated_latency": self.latency,
            "simulated_failure_rate": self.failure_rate
        }
