import React from 'react';
import { CheckCircle2, XCircle } from 'lucide-react';

const ReportScope = () => {
    return (
        <div style={{
            width: '100%',
            maxWidth: '600px',
            margin: '2rem auto',
            textAlign: 'left'
        }}>
            <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-primary)' }}>
                Report Scope
            </h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div className="glass-panel" style={{ padding: '1.25rem', borderRadius: '12px' }}>
                    <div style={{
                        fontSize: '0.875rem',
                        color: 'var(--color-risk-low)',
                        fontWeight: 600,
                        marginBottom: '0.75rem',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '0.5rem'
                    }}>
                        <CheckCircle2 size={16} /> INCLUDED
                    </div>
                    <ul style={{ listStyle: 'none', padding: 0, margin: 0, fontSize: '0.875rem', color: 'var(--color-secondary)' }}>
                        <li style={{ marginBottom: '0.5rem' }}>Fundamental Analysis</li>
                        <li style={{ marginBottom: '0.5rem' }}>Sentiment Trends</li>
                        <li style={{ marginBottom: '0.5rem' }}>Risk Assessment</li>
                        <li>Competitive Landscape</li>
                    </ul>
                </div>

                <div className="glass-panel" style={{ padding: '1.25rem', borderRadius: '12px', border: '1px solid rgba(239, 68, 68, 0.2)' }}>
                    <div style={{
                        fontSize: '0.875rem',
                        color: 'var(--color-risk-high)',
                        fontWeight: 600,
                        marginBottom: '0.75rem',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '0.5rem'
                    }}>
                        <XCircle size={16} /> EXCLUDED
                    </div>
                    <ul style={{ listStyle: 'none', padding: 0, margin: 0, fontSize: '0.875rem', color: 'var(--color-secondary)' }}>
                        <li style={{ marginBottom: '0.5rem' }}>Price Predictions</li>
                        <li style={{ marginBottom: '0.5rem' }}>Buy/Sell Signals</li>
                        <li style={{ marginBottom: '0.5rem' }}>Short-term Trading</li>
                        <li>Financial Advice</li>
                    </ul>
                </div>
            </div>

            <p style={{
                fontSize: '0.75rem',
                color: 'var(--color-secondary)',
                marginTop: '1.5rem',
                textAlign: 'center',
                fontStyle: 'italic'
            }}>
                * This report is generated by AI for informational purposes only.
            </p>
        </div>
    );
};

export default ReportScope;
