import logging
import json
import sys
import traceback
from datetime import datetime
from flask import request, has_request_context

class JSONFormatter(logging.Formatter):
    """
    Datadog/ElasticSearch compatible JSON struct logger.
    Automatically enriches logs with HTTP request context, Trace IDs, 
    and proper string escaping for centralized logging observability infrastructures.
    """
    def format(self, record):
        log_entry = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "level": record.levelname,
            "message": record.getMessage(),
            "logger": record.name,
            "path": record.pathname,
            "line": record.lineno,
        }
        
        # Inject standard stack traces if present
        if record.exc_info:
            log_entry["exception"] = "".join(traceback.format_exception(*record.exc_info))

        # Inject request-level trace identifiers automatically if available
        if has_request_context():
            log_entry["http"] = {
                "method": request.method,
                "url": request.url,
                "remote_ip": request.remote_addr,
                "user_agent": request.headers.get("User-Agent")
            }
            # Look for explicit trace ID generated by edge proxy
            trace_id = request.headers.get("X-Request-Id")
            if trace_id:
                log_entry["trace_id"] = trace_id

        return json.dumps(log_entry)

def setup_production_logging():
    """
    Reconfigures the root logger to bypass default text formatting and 
    instead push strict JSON outputs directly to stdout.
    """
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.INFO)

    # Remove all existing handlers (like default werkzeug output)
    for handler in root_logger.handlers[:]:
        root_logger.removeHandler(handler)

    json_handler = logging.StreamHandler(sys.stdout)
    json_handler.setFormatter(JSONFormatter())
    
    root_logger.addHandler(json_handler)
    logging.getLogger("werkzeug").setLevel(logging.WARNING) # Mute generic HTTP logs
    
    root_logger.info("JSON Production Logging Pipeline Initialized Successfully.")
